version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mishna_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mishna_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mishna_network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mishna_server
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mishna_db
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - mishna_network

volumes:
  postgres_data:

networks:
  mishna_network:
    driver: bridge
